## Numpy

In [2]:
import numpy as np

In [7]:
lis = [[1, 2], [3, 4]]
a = np.array(lis, dtype = 'int64')
print(a)
print(type(a))
print(a.dtype)
print(a.shape)
print(a.T)

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
int64
(2, 2)
[[1 3]
 [2 4]]


In [16]:
b = np.zeros((2, 2))
c = np.ones((2, 2))
d = np.full((2, 2), 5)
e = np.eye(2)
f = np.random.random((2, 2))
print(b)
print(c)
print(d)
print(e)
print(f)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[5 5]
 [5 5]]
[[1. 0.]
 [0. 1.]]
[[0.18754349 0.3419585 ]
 [0.74301006 0.02525437]]


In [17]:
a+b

array([[1., 2.],
       [3., 4.]])

In [18]:
np.add(a, b)

array([[1., 2.],
       [3., 4.]])

In [19]:
a-b

array([[1., 2.],
       [3., 4.]])

In [20]:
np.subtract(a, b)

array([[1., 2.],
       [3., 4.]])

In [21]:
a*b

array([[0., 0.],
       [0., 0.]])

In [22]:
np.multiply(a, b)

array([[0., 0.],
       [0., 0.]])

In [24]:
a/f

array([[  5.33209648,   5.84866286],
       [  4.03763037, 158.38839899]])

In [25]:
np.divide(a, f)

array([[  5.33209648,   5.84866286],
       [  4.03763037, 158.38839899]])

In [26]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [28]:
a.dot(c)

array([[3., 3.],
       [7., 7.]])

In [29]:
np.dot(a, b)

array([[0., 0.],
       [0., 0.]])

In [30]:
sum(a)

array([4, 6], dtype=int64)

In [31]:
np.sum(a, axis = 0)

array([4, 6], dtype=int64)

In [32]:
np.sum(a, axis = 1)

array([3, 7], dtype=int64)

In [33]:
np.stack((a, b), axis = 0)

array([[[1., 2.],
        [3., 4.]],

       [[0., 0.],
        [0., 0.]]])

In [34]:
np.stack((a, b), axis = 1)

array([[[1., 2.],
        [0., 0.]],

       [[3., 4.],
        [0., 0.]]])

In [35]:
a.reshape(1, 4)

array([[1, 2, 3, 4]], dtype=int64)

In [42]:
print(a)

[[1 2]
 [3 4]]


In [41]:
np.random.shuffle(a)

In [44]:
print(np.arange(20).reshape(5, -1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [49]:
np.random.choice(a.reshape(-1, ))

4